name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'  # Recommended LTS version

      # 3. Install dependencies (use npm instead of yarn for consistency)
      - run: npm ci  # Clean install (faster than regular install)

      # 4. Build project
      - run: npm run build

      # 5. Add .nojekyll file (critical for Three.js)
      - run: touch ./dist/.nojekyll

      # 6. Deploy to GH Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false  # Clean old files
          force_orphan: true # Single commit deployment
